import type {
  AuditEntry,
  Incident,
  NetworkLink,
  NetworkNode,
  TelemetryPoint,
} from "@/lib/types";

export const networkNodes: NetworkNode[] = [
  {
    id: "core-del-01",
    name: "DEL-CORE-01",
    role: "core",
    region: "Delhi",
    x: 48,
    y: 35,
    status: "warning",
    latency: 42,
    packetLoss: 1.8,
    cpu: 73,
    temperature: 61,
    uptime: "187d 04h",
    interfaces: 48,
  },
  {
    id: "core-mum-01",
    name: "MUM-CORE-01",
    role: "core",
    region: "Mumbai",
    x: 32,
    y: 69,
    status: "healthy",
    latency: 18,
    packetLoss: 0.1,
    cpu: 42,
    temperature: 48,
    uptime: "243d 19h",
    interfaces: 48,
  },
  {
    id: "core-hyd-01",
    name: "HYD-CORE-01",
    role: "core",
    region: "Hyderabad",
    x: 58,
    y: 72,
    status: "healthy",
    latency: 21,
    packetLoss: 0.2,
    cpu: 38,
    temperature: 46,
    uptime: "202d 11h",
    interfaces: 36,
  },
  {
    id: "pe-jai-02",
    name: "JAI-PE-02",
    role: "provider-edge",
    region: "Jaipur",
    x: 25,
    y: 29,
    status: "healthy",
    latency: 16,
    packetLoss: 0.1,
    cpu: 34,
    temperature: 44,
    uptime: "119d 08h",
    interfaces: 24,
  },
  {
    id: "pe-lko-03",
    name: "LKO-PE-03",
    role: "provider-edge",
    region: "Lucknow",
    x: 72,
    y: 30,
    status: "critical",
    latency: 96,
    packetLoss: 4.7,
    cpu: 88,
    temperature: 69,
    uptime: "42d 16h",
    interfaces: 24,
  },
  {
    id: "pe-ahm-01",
    name: "AHM-PE-01",
    role: "provider-edge",
    region: "Ahmedabad",
    x: 17,
    y: 53,
    status: "healthy",
    latency: 14,
    packetLoss: 0,
    cpu: 31,
    temperature: 43,
    uptime: "274d 02h",
    interfaces: 24,
  },
  {
    id: "pe-blr-02",
    name: "BLR-PE-02",
    role: "provider-edge",
    region: "Bengaluru",
    x: 48,
    y: 91,
    status: "healthy",
    latency: 19,
    packetLoss: 0.1,
    cpu: 47,
    temperature: 49,
    uptime: "96d 22h",
    interfaces: 24,
  },
  {
    id: "ce-pat-07",
    name: "PAT-CE-07",
    role: "customer-edge",
    region: "Patna",
    x: 89,
    y: 46,
    status: "warning",
    latency: 68,
    packetLoss: 2.3,
    cpu: 76,
    temperature: 62,
    uptime: "31d 05h",
    interfaces: 12,
  },
];

export const networkLinks: NetworkLink[] = [
  { id: "l1", source: "core-del-01", target: "core-mum-01", utilization: 68, capacityGbps: 40, status: "healthy", label: "LSP-DEL-MUM-A" },
  { id: "l2", source: "core-del-01", target: "core-hyd-01", utilization: 83, capacityGbps: 40, status: "warning", label: "LSP-DEL-HYD-A" },
  { id: "l3", source: "core-mum-01", target: "core-hyd-01", utilization: 54, capacityGbps: 40, status: "healthy", label: "LSP-MUM-HYD-A" },
  { id: "l4", source: "pe-jai-02", target: "core-del-01", utilization: 41, capacityGbps: 10, status: "healthy", label: "LSP-JAI-DEL-02" },
  { id: "l5", source: "pe-lko-03", target: "core-del-01", utilization: 94, capacityGbps: 10, status: "critical", label: "LSP-LKO-DEL-03" },
  { id: "l6", source: "pe-ahm-01", target: "core-mum-01", utilization: 36, capacityGbps: 10, status: "healthy", label: "LSP-AHM-MUM-01" },
  { id: "l7", source: "pe-blr-02", target: "core-hyd-01", utilization: 51, capacityGbps: 10, status: "healthy", label: "LSP-BLR-HYD-02" },
  { id: "l8", source: "ce-pat-07", target: "pe-lko-03", utilization: 87, capacityGbps: 5, status: "warning", label: "PW-PAT-LKO-07" },
  { id: "l9", source: "ce-pat-07", target: "core-hyd-01", utilization: 32, capacityGbps: 5, status: "healthy", label: "PW-PAT-HYD-BK" },
];

export const initialIncidents: Incident[] = [
  {
    id: "INC-2047",
    title: "Probable LSP degradation",
    summary: "Queue growth and route churn indicate a likely service-impacting event on the Lucknow–Delhi path.",
    severity: "critical",
    status: "active",
    confidence: 91,
    predictedIn: 18,
    detectedAt: "23:42:18",
    affectedNodes: ["LKO-PE-03", "DEL-CORE-01", "PAT-CE-07"],
    signals: [
      "Egress queue depth +184% over 12 minutes",
      "Six route-flap events within the observation window",
      "Packet loss crossed 4.5% on LSP-LKO-DEL-03",
    ],
    recommendedAction: "Shift priority traffic to PW-PAT-HYD-BK, damp the unstable route, and inspect the LKO-PE-03 egress interface.",
  },
  {
    id: "INC-2042",
    title: "Thermal drift detected",
    summary: "Sustained temperature increase on DEL-CORE-01 remains below the shutdown threshold.",
    severity: "medium",
    status: "investigating",
    confidence: 78,
    predictedIn: 46,
    detectedAt: "23:17:04",
    affectedNodes: ["DEL-CORE-01"],
    signals: [
      "Chassis temperature +9°C over baseline",
      "Fan group 2 operating at 92%",
    ],
    recommendedAction: "Verify airflow and inspect fan group 2 during the next maintenance window.",
  },
  {
    id: "INC-2036",
    title: "Tunnel flap contained",
    summary: "Automated dampening stabilized the secondary Hyderabad path.",
    severity: "low",
    status: "contained",
    confidence: 96,
    predictedIn: 0,
    detectedAt: "22:51:39",
    affectedNodes: ["HYD-CORE-01"],
    signals: ["Tunnel state stable for 34 minutes"],
    recommendedAction: "Continue observation; no operator action required.",
  },
];

export const initialAuditEntries: AuditEntry[] = [
  { id: "AUD-8711", timestamp: "23:44:02", actor: "operator.jsoni", action: "Viewed predictive evidence", target: "INC-2047", result: "recorded" },
  { id: "AUD-8710", timestamp: "23:42:19", actor: "prediction.engine", action: "Raised critical forecast", target: "LSP-LKO-DEL-03", result: "recorded" },
  { id: "AUD-8709", timestamp: "23:39:51", actor: "telemetry.collector", action: "Validated stream integrity", target: "8 network nodes", result: "recorded" },
  { id: "AUD-8708", timestamp: "23:17:05", actor: "prediction.engine", action: "Raised thermal advisory", target: "DEL-CORE-01", result: "recorded" },
  { id: "AUD-8707", timestamp: "22:52:14", actor: "operator.jsoni", action: "Approved route dampening", target: "INC-2036", result: "approved" },
];

export const initialTelemetry: TelemetryPoint[] = Array.from({ length: 30 }, (_, index) => {
  const rising = Math.max(0, index - 17);
  return {
    timestamp: Date.now() - (29 - index) * 60_000,
    latency: 28 + Math.sin(index / 2.8) * 4 + rising * 1.15,
    packetLoss: 0.3 + Math.max(0, index - 20) * 0.19,
    utilization: 58 + Math.sin(index / 4) * 6 + rising * 1.65,
    risk: 21 + Math.max(0, index - 15) * 4.2,
  };
});
